# Generated by Django 4.0 on 2021-12-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtToEarningsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zip', models.CharField(max_length=60)),
                ('institutionType', models.CharField(max_length=60)),
                ('cipCode', models.CharField(max_length=60)),
                ('cipName', models.CharField(max_length=60)),
                ('credentialLevel', models.CharField(max_length=60)),
                ('debtToEarningsAnnualRate', models.FloatField()),
                ('meanAnnualEarningsFromSsa', models.FloatField()),
                ('medianAnnualEarningsfromSsa', models.FloatField()),
            ],
        ),
    ]
