# Generated by Django 4.0 on 2021-12-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_debttoearningsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debttoearningsdata',
            name='cipName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='debttoearningsdata',
            name='institutionName',
            field=models.CharField(max_length=200),
        ),
    ]
