export const uniqueInstituteTypes = ["PUBLIC 2 TO 3 YEARS", "PUBLIC 4 YEARS OR MORE",
"PROPRIETARY 4 YEARS OR MORE", "PRIVATE, NOT-FOR-PROFIT 4 YEARS OR MORE",
"PROPRIETARY 2 TO 3 YEARS", "PRIVATE, NOT-FOR-PROFIT 2 TO 3 YEARS",
"PUBLIC LESS THAN 2 YEARS", "PROPRIETARY LESS THAN 2 YEARS",
"PRIVATE, NOT-FOR-PROFIT LESS THAN 2 YEARS"]

export const uniqueCredentialLevels = ["01 - UNDERGRADUATE CERTIFICATE", "08 - GRADUATE CERTIFICATE",
"05 - MASTERS DEGREE" ,"03 - BACHELORS DEGREE",
"04 - POST BACCALAUREATE CERTIFICATE" ,"02 - ASSOCIATES DEGREE",
"06 - DOCTORAL DEGREE", "07 - FIRST PROFESSIONAL DEGREE"]
